<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>dusk-module</groupId>
    <artifactId>dusk-module-workflow-group</artifactId>
    <version>1.1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <modules>
        <module>dusk-module-workflow-shared</module>
        <module>dusk-module-workflow</module>
    </modules>

    <repositories>
        <repository>
            <id>github-dusk-module-parent</id>
            <url>https://maven.pkg.github.com/MouckIS/dusk-module-parent</url>
            <snapshots>
                <enabled>true</enabled>
            </snapshots>
        </repository>
    </repositories>
    <distributionManagement>
        <repository>
            <id>github-dusk-module-workflow</id>
            <url>https://maven.pkg.github.com/MouckIS/dusk-module-workflow</url>
        </repository>
    </distributionManagement>
</project>
