server:
  port: ${SERVER_PORT:80}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://db-server:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  #    active: dev
  application:
    name: ${SPRING_APPLICATION_NAME:dusk-module-workflow}
logging:
  level:
    org.orion: ${LOGGING_LEVEL_ORION:INFO}
  config: classpath:conf/logback-prod.xml