server:
  port: ${SERVER_PORT:53199}

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://192.168.105.105:5432/crux-workflow}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:unitech}
  application:
    name: ${SPRING_APPLICATION_NAME:dusk-module-workflow}
  rabbitmq:
    is-enabled: ${SPRING_RABBITMQ_ISENABLED:false}
  flyway:
    enabled: false
    table: flyway_schema_history_activiti

logging:
  level:
    org.orion: ${LOGGING_LEVEL_ORION:DEBUG}

dubbo:
  protocol:
    name: dubbo
    port: -1
  registry:
    address: zookeeper://${spring.cloud.zookeeper.connect-string}
  scan:
    base-packages: com.dusk.module.workflow.service
  consumer:
    check: false

activiti:
  async-executor-activate: false
  check-process-definitions: false

  #这是seata单机配置，不适合集群
seata:
  enabled: false
  service:
    vgroup-mapping:
      dusk-module-workflow-seata-service-group: default
    grouplist:
      default: 192.168.105.105:8091
