spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:sit}
    include: common-${spring.profiles.active}
  application:
    name: ${SPRING_APPLICATION_NAME:dusk-module-workflow}
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml
dubbo:
  application:
    # todo: 暂时禁用序列化安全检查，后续补充自定义序列化白名单
    serialize-check-status: DISABLE